# Acinar Analysis GUI
*Unified pipeline for all 3D acinar image quantification*

## Available analyses
| Analysis | What it measures | Required inputs |
|---|---|---|
| Acinus Shape | Acinus volume (µm³) and roundness | Image folder only |
| Cell & Nuclear Shape | Cell/nuclear volume, roundness, neighbours | Image + nuclear mask + membrane mask folders |
| Protein Polarisation | Protein intensity vs radial distance from centre | Image folder + protein channel |
| Apoptosis (C3) | C3+ cell count, spatial distribution, nuclei count | Image + C3 mask + nuclear mask folders |
| Protein Proximity | Protein intensity near dying vs non-dying cells | Image + C3/nuclear mask folders + proximity channel |
| Proliferation (EdU) | EdU+ dividing vs non-dividing cell count & position | Image + EdU mask + nuclear mask folders |
| Mitochondria | Per-cell mito count, volume, mito/cell ratio, distance from nucleus | Image + nuclear mask + membrane mask + mito mask folders |

## How to use
1. Run the cell below to open the GUI window
2. Select your **Image Folder**, any required **mask folders**, and an **Output Directory**
3. Set **channel indices** (–1 = not used)
4. Tick the **analyses** you want to run
5. Click **Run Analysis** — the GUI window closes and analysis runs with progress in the terminal
6. Results are saved as CSVs (one per analysis type) in your output directory
7. If **Save QC Plots** is ticked, overlay PNGs are saved in an `output_dir/qc_plots/` folder

---
## Launch the GUI
Run the cell below to open the analysis window. It provides:
- **Folder selectors** for images, each mask type, and an output directory
- **Channel configuration** (nuclear, membrane, protein, C3, EdU, mito, proximity)
- **Analysis checkboxes** — validates required folders/channels before running
- **QC plots** saved as PNG overlays for quality control

When you click **Run Analysis**, the GUI closes and batch processing runs
with a tqdm progress bar visible in the notebook output. Results + QC plots
are saved to the output directory you selected.

In [ ]:
%gui qt
from acinar_gui import launch_and_run

results = launch_and_run()

============================================================
Running analyses: acinus_shape, apoptosis
Image folder:     C:\Users\taylorhearn\Dropbox\Shared_With_Me\ROCKi_experiments\c3_actin_analysis_12G10_live_incubation\d0\d0_dapi_lamV_actin_c3_tif
Output CSV:       C:\Users\taylorhearn\Dropbox\Shared_With_Me\ROCKi_experiments\c3_actin_analysis_12G10_live_incubation\d0\test_outputs\acinar_results.csv
QC plots:         C:\Users\taylorhearn\Dropbox\Shared_With_Me\ROCKi_experiments\c3_actin_analysis_12G10_live_incubation\d0\test_outputs\qc_plots
============================================================
Found 19 images. Running analyses: ['acinus_shape', 'apoptosis']

Acinar Analysis:  32%|███▏      | 6/19 [06:30<10:13, 47.23s/it]

In [ ]:
# Inspect results (optional)
if results:
    for name, df in results.items():
        print(f"\n--- {name} ({len(df)} rows) ---")
        display(df.head())

--- acinus_shape (19 rows) ---

,vol_um,roundness,flag,filename,well,day,cell_type,condition,treatment,image_type
0,249929.453752,0.759838,None,well1_wt_d0_c3_lamv_actin004_1.75x_cmle.tif,1,0,WT,blank,untreated,"blank, d0"
1,173835.255711,0.859986,None,well1_wt_d0_c3_lamv_actin005_1.75x_cmle.tif,1,0,WT,blank,untreated,"blank, d0"
2,139714.101134,0.792559,None,well1_wt_d0_c3_lamv_actin006_2x_cmle.tif,1,0,WT,blank,untreated,"blank, d0"
3,164522.298772,0.718785,None,well1_wt_d0_c3_lamv_actin007_2x_cmle.tif,1,0,WT,blank,untreated,"blank, d0"
4,157409.149607,0.707245,None,well1_wt_d0_c3_lamv_actin008_2x_cmle.tif,1,0,WT,blank,untreated,"blank, d0"

--- apoptosis (151 rows) ---

,label,centroid-0,centroid-1,centroid-2,c3_volume_um,normalised_distance,acinus_volume_um,acinus_roundness,number_of_nuclei,flag,filename,well,day,cell_type,condition,treatment,image_type
0,1,153.102870,105.662772,77.631700,2289.135676,0.334934,279796.901978,0.76308,71,None,well1_wt_d0_c3_lamv_actin004_1.75x_cmle.tif,1,0,WT,blank,untreated,"blank, d0"
1,2,120.629031,147.353058,60.803727,3738.684109,0.647194,279796.901978,0.76308,71,None,well1_wt_d0_c3_lamv_actin004_1.75x_cmle.tif,1,0,WT,blank,untreated,"blank, d0"
2,3,150.166408,127.740642,145.552159,1635.700714,0.239925,279796.901978,0.76308,71,None,well1_wt_d0_c3_lamv_actin004_1.75x_cmle.tif,1,0,WT,blank,untreated,"blank, d0"
3,4,176.642992,158.892820,153.738005,704.758167,0.113871,279796.901978,0.76308,71,None,well1_wt_d0_c3_lamv_actin004_1.75x_cmle.tif,1,0,WT,blank,untreated,"blank, d0"
4,5,76.344380,96.021076,109.904427,455.508534,0.673086,279796.901978,0.76308,71,None,well1_wt_d0_c3_lamv_actin004_1.75x_cmle.tif,1,0,WT,blank,untreated,"blank, d0"

## Plot Results
Run the cell below to launch the plotting GUI. Select the folder containing the output CSVs from the analysis above.

In [ ]:
from plotting_gui import launch_and_run as launch_plotting
figs = launch_plotting()